Fixes a bug in writetable's append parameter.
Previous to the fix, the following resulted in an error:
using DataFrames
df = DataFrames.DataFrame(a = @data([1, 2]))
filename = "testme.csv"
isfile(filename) && rm(filename)
writetable(filename, df, append = true)
writetable(filename, df, append = true)

ERROR: LoadError: KeyError: key "Column names don't match names in file"
not found

The changes in abstractdataframe/io.jl resolve the issue.
A test for this particular case has been added in test/io.jl