update docs for join on (left, right) tuple
I tried to use a tuple but in DataFrames 1.3 I got this error:

ERROR: ArgumentError: Using a `Tuple{Symbol, Symbol}` or a vector containing such tuples as a value of `on` keyword argument is not supported: use `Pair{Symbol, Symbol}` instead.

So I'm assuming this option is no longer supported.